# Generated by Django 5.0.3 on 2024-05-02 04:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompletedTasks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("params", models.TextField()),
                ("made_at", models.DateTimeField(auto_now_add=True)),
                ("run_at", models.DateTimeField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WaitingTasks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("params", models.TextField()),
                ("made_at", models.DateTimeField(auto_now_add=True)),
                ("run_at", models.DateTimeField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
