# Generated by Django 5.0.3 on 2024-05-03 01:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backtasks", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CompletedTasks",
            new_name="CompletedTask",
        ),
        migrations.RenameModel(
            old_name="WaitingTasks",
            new_name="WaitingTask",
        ),
    ]
